manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kevinpastor #new entry
      url-base: https://github.com/kevinpastor #new entry
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-elemental #new entry
      remote: kevinpastor #new entry
      revision: main #new entry
  self:
    path: config